Repository EpicGames/PixelStreamingInfrastructure, pull requests merged in 2023-07, with the labels that each got.

#299 Fix video res and frames dropped not updating in stats panel
  SignallingWebServer/scripts/webRtcPlayer.js
Labels: bug, regression

#300 Duplicate #299for UE5.0
  SignallingWebServer/scripts/webRtcPlayer.js
Labels: bug, regression

#303 Show player count in stats panel
  Frontend/library/src/PixelStreaming/PixelStreaming.ts
  Frontend/library/src/Util/EventEmitter.ts
  Frontend/library/src/WebRtcPlayer/WebRtcPlayerController.ts
  Frontend/library/src/WebSockets/SignallingProtocol.ts
  Frontend/library/src/WebSockets/WebSocketController.ts
  Frontend/ui-library/src/Application/Application.ts
  Frontend/ui-library/src/UI/StatsPanel.ts
Labels: enhancement, auto-backport, auto-backport-to-UE5.2, auto-backport-to-UE5.3

#310 Fix: Firefox console errors `TypeError: this.preferredCodec.split is not a function`
  Frontend/library/src/Config/SettingOption.ts
  Frontend/library/src/PeerConnectionController/PeerConnectionController.ts
Labels: bug, regression, auto-backport, auto-backport-to-UE5.2, auto-backport-to-UE5.3, awaiting-approval

#316 Ensure touch is relative to absolute location of parent rect
  Frontend/library/src/Inputs/TouchController.ts
Labels: bug, auto-backport, auto-backport-to-UE5.2, auto-backport-to-UE5.3

#325 Fixed [BUG] - TypeError: console.warning is not a function
  SignallingWebServer/cirrus.js
Labels: auto-backport, auto-backport-to-UE5.2

#332 Properly inject new params into SDP to get stereo back on Chrome
  Frontend/library/src/PeerConnectionController/PeerConnectionController.ts
Labels: auto-backport, auto-backport-to-UE5.2, auto-backport-to-UE5.3

#336 Add: Protocol structures can now contain strings
  Frontend/implementations/typescript/src/player.ts
  Frontend/library/src/Inputs/KeyboardController.ts
  Frontend/library/src/PixelStreaming/PixelStreaming.ts
  Frontend/library/src/UeInstanceMessage/SendDescriptorController.ts
  Frontend/library/src/UeInstanceMessage/SendMessageController.ts
  Frontend/library/src/UeInstanceMessage/StreamMessageController.ts
  Frontend/library/src/UeInstanceMessage/TwoWayMap.ts
  Frontend/library/src/WebRtcPlayer/WebRtcPlayerController.ts
  Frontend/library/src/pixelstreamingfrontend.ts
  package-lock.json
Labels: enhancement, awaiting-approval
